name: CustomSkulls
main: com.timvisee.customskulls.CustomSkulls
description: 'Make mobs and players drop skulls'
version: 0.2
author: timvisee
website: http://timvisee.com/
softdepend: [Vault] #hack to fix trove errors
commands:
  customskulls:
    description: Custom Skulls command
    usage: /customskulls
  customskull:
    description: Custom Skulls command
    usage: /customskull
  skulls:
      description: Custom Skulls command
      usage: /skulls